### ISSUE TITLE
Give already-connected app permission on new accounts automatically

### ISSUE THREAD

**Issue by rossbulat** [TalismanSociety/talisman-connect#24]
Currently if I create a new account in Talisman extension and I have a Dapp open - one which I have an existing Talisman account connected to - I still need to go to trusted sites and enable the app be connected to the new account.

Could a newly created account already trust a dapp that another account has trusted? Otherwise we need to make very clear in-app that you need to follow this trust workflow which involves delving into multi-level menus in the extension.

**Comment by chidg** [comment]
Hi @rossbulat, this goes back a while, apologies for the lack of response. We are currently re-invigorating this repo. I guess you made the comment here because at that point the Talisman extension repo was not public, but this is really related to Talisman extension functionality. Currently we do not automatically authorise sites for a new account when added to the wallet, however we are considering doing so when the site is set to 'connect all'. We've also made those options easier to get to, they're only one menu deep from the popup itself, and the button for that is more prominent. I'll close this for now, but please make another issue in the Talisman extension monorepo if you have more comments.
